added updated files for skaffold and cloud build

diff --git a/.github/workflows/ci-pipeline.yaml b/.github/workflows/ci-pipeline.yaml
--- a/.github/workflows/ci-pipeline.yaml
+++ b/.github/workflows/ci-pipeline.yaml
@@ -418,3 +418,53 @@ jobs:
           docker build -t "$GAR_INFO"/"$RABBITMQ_APP_NAME":"$TAG" rabbitmq/
           gcloud info
           docker push "$GAR_INFO"/"$RABBITMQ_APP_NAME":"$TAG"
+
+  deploy-to-gcp-learn:
+    name: Deploy to GCP Dev learn
+    needs: [build-cart,build-catalogue,build-dispatch,build-mongo,build-mysql,build-payment,build-rabbitmq,build-ratings,build-redis,build-shipping,build-user,build-web]
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+                        
+      - name: Setup GCP Service Account
+        uses: "google-github-actions/auth@v0"
+        with:
+          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
+      
+      - name: Set up Cloud SDK
+        uses: 'google-github-actions/setup-gcloud@v0'
+
+      - name: Call Google Cloud Deploy
+        run: |
+         cd K8s
+         date_var=`date +%m%d%y-%H%M`
+         echo "date_var=$date_var" >> $GITHUB_ENV
+         gcloud deploy releases create rel-$date_var --delivery-pipeline=robot-shop --region=us-central1
+      
+      - name: verify if the rollout is success
+        run: |
+         gcloud deploy rollouts describe rel-${{ env.date_var }}-to-learn-0001 --release=rel-${{ env.date_var }} --delivery-pipeline=robot-shop --region=us-central1
+         sleep 60
+         counter=0
+         while [ $counter -lt 20 ]
+         do
+         export some_val=`gcloud deploy rollouts describe rel-${{ env.date_var }}-to-learn-0001 --release=rel-${{ env.date_var }} --delivery-pipeline=robot-shop --region=us-central1 | grep state: | cut -f2 -d: | cut -d' ' -f2`
+         if [ "$some_val" == "IN_PROGRESS" ]
+         then
+           echo "Deployment in Progress Time is: `date`"
+             sleep 30
+             continue
+         elif [ "$some_val" == "SUCCEEDED" ]
+         then
+           echo "Deployment is Succeeded Time is: `date`	"
+             exit 0
+         else
+           echo "Deployment Failed Time is: `date`"
+             exit 1
+         fi
+           counter=$(( $counter + 1))
+         
+           done
